<div class="row">
    <div class="col-md-4 mb-3"><label class="form-label">Código institucional</label><input name="codigo" class="form-control @error('codigo') is-invalid @enderror" value="{{ old('codigo', $estudiante->codigo ?? '') }}">@error('codigo')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-8 mb-3"><label class="form-label">Nombre completo</label><input name="nombre" class="form-control @error('nombre') is-invalid @enderror" value="{{ old('nombre', $estudiante->nombre ?? '') }}" required>@error('nombre')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-5 mb-3"><label class="form-label">Correo <span class="text-muted">(opcional)</span></label><input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email', $estudiante->email ?? '') }}">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-5 mb-3"><label class="form-label">Carrera</label><select name="carrera_id" class="form-select @error('carrera_id') is-invalid @enderror" required><option value="">Seleccione…</option>@foreach($carreras as $carrera)<option value="{{ $carrera->id }}" @selected(old('carrera_id', $estudiante->carrera_id ?? '') == $carrera->id)>{{ $carrera->nombre }}</option>@endforeach</select>@error('carrera_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-2 mb-3"><label class="form-label">Gestión de ingreso</label><input type="number" name="gestion_ingreso" min="2000" max="{{ date('Y') + 1 }}" class="form-control @error('gestion_ingreso') is-invalid @enderror" value="{{ old('gestion_ingreso', $estudiante->gestion_ingreso ?? '') }}">@error('gestion_ingreso')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6 mb-3"><label class="form-label">Cuenta de acceso <span class="text-muted">(opcional)</span></label><select name="user_id" class="form-select @error('user_id') is-invalid @enderror"><option value="">No necesita iniciar sesión</option>@foreach($cuentas as $cuenta)<option value="{{ $cuenta->id }}" @selected(old('user_id', $estudiante->user_id ?? '') == $cuenta->id)>{{ $cuenta->name }} · {{ $cuenta->email }}</option>@endforeach</select>@error('user_id')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">Vincúlala solo si el estudiante debe consultar sus proyectos y reportes.</div></div>
</div>
<p class="form-text">Registrar un estudiante aquí no crea una cuenta de acceso al sistema.</p>
<button class="btn btn-primary" type="submit">{{ $textoBoton }}</button>
<a href="{{ route('estudiantes.index') }}" class="btn btn-secondary">Cancelar</a>
