<x-app-layout>
    <x-slot name="header"><div class="page-title"><h2>Docentes tutores</h2><span>Directorio académico para la asignación de proyectos</span></div></x-slot>
    <div class="container py-4">
        @if(session('success'))<x-flash-success :message="session('success')" />@endif
        <div class="d-flex justify-content-between align-items-center gap-3 flex-wrap mb-3"><div><h3 class="user-section-title">Directorio docente</h3><p class="user-section-copy">Un docente tutor no necesita tener una cuenta de acceso.</p></div><a href="{{ route('docentes.create') }}" class="btn btn-primary"><i class="bi bi-person-plus me-1"></i> Nuevo docente</a></div>
        <form method="GET" class="d-flex gap-2 mb-3"><input type="search" name="buscar" value="{{ request('buscar') }}" class="form-control" placeholder="Buscar por nombre, código o correo"><button class="btn btn-primary">Buscar</button><a href="{{ route('docentes.index') }}" class="btn btn-outline-secondary">Limpiar</a></form>
        <div class="table-responsive"><table role="table" class="table mobile-record-table table-striped table-bordered align-middle"><thead role="rowgroup"><tr role="row"><th scope="col" role="columnheader">Código</th><th scope="col" role="columnheader">Nombre</th><th scope="col" role="columnheader">Carreras</th><th scope="col" role="columnheader">Cuenta</th><th scope="col" role="columnheader">Estado</th><th scope="col" role="columnheader">Acciones</th></tr></thead><tbody role="rowgroup">
            @forelse($docentes as $docente)<tr role="row" class="{{ $docente->activo ? '' : 'inactive-record' }}"><td role="cell" data-label="Código">{{ $docente->codigo ?: '—' }}</td><td role="cell" data-label="Nombre"><strong>{{ $docente->nombre }}</strong><small class="d-block text-muted">{{ $docente->email ?: 'Sin correo' }}</small></td><td role="cell" data-label="Carreras">@forelse($docente->carreras as $carrera)<span class="badge bg-light text-dark border me-1 mb-1">{{ $carrera->codigo }}</span>@empty<span class="text-muted">Sin asignar</span>@endforelse</td><td role="cell" data-label="Cuenta">{{ $docente->user_id ? 'Vinculada' : 'No requerida' }}</td><td role="cell" data-label="Estado"><span class="badge {{ $docente->activo ? 'bg-success' : 'bg-secondary' }}">{{ $docente->activo ? 'Activo' : 'Inactivo' }}</span></td><td role="cell" data-label="Acciones"><a href="{{ route('docentes.edit', $docente) }}" class="btn btn-sm btn-warning">Editar</a> <form action="{{ route('docentes.toggle-activo', $docente) }}" method="POST" class="d-inline">@csrf @method('PATCH')<button class="btn btn-sm {{ $docente->activo ? 'btn-secondary' : 'btn-success' }}">{{ $docente->activo ? 'Desactivar' : 'Activar' }}</button></form></td></tr>
            @empty<tr role="row"><td role="cell" colspan="6" class="text-center py-4">No hay docentes registrados.</td></tr>@endforelse
        </tbody></table></div>{{ $docentes->links() }}
    </div>
</x-app-layout>
